var searchData=
[
  ['table_20des_20matières_0',['📖 Table des Matières',['../md_README.html#autotoc_md3',1,'']]],
  ['tags_20et_20releases_1',['Tags et Releases',['../md_README.html#autotoc_md126',1,'']]],
  ['tdd_20adapté_2',['1. Test-Driven Development (TDD) Adapté',['../md_README.html#autotoc_md72',1,'']]],
  ['technique_3',['FAQ Technique',['../md_README.html#autotoc_md151',1,'']]],
  ['techniques_20c_4',['Références Techniques C++',['../md_README.html#autotoc_md132',1,'']]],
  ['technologies_20utilisées_5',['Technologies Utilisées',['../md_README.html#autotoc_md8',1,'']]],
  ['template_20de_20bug_20report_6',['Template de Bug Report',['../md_README.html#autotoc_md162',1,'']]],
  ['template_20de_20commit_7',['Template de Commit',['../md_README.html#autotoc_md160',1,'']]],
  ['template_20de_20pull_20request_8',['Template de Pull Request',['../md_README.html#autotoc_md161',1,'']]],
  ['templates_20utiles_9',['📝 Templates Utiles',['../md_README.html#autotoc_md159',1,'']]],
  ['temps_10',['Gestion du Temps',['../md_README.html#autotoc_md76',1,'']]],
  ['test_20driven_20development_20tdd_20adapté_11',['1. Test-Driven Development (TDD) Adapté',['../md_README.html#autotoc_md72',1,'']]],
  ['tests_12',['tests',['../md_README.html#autotoc_md92',1,'Exécution des Tests'],['../md_README.html#autotoc_md95',1,'Types de Tests']]],
  ['tests_20échoués_13',['Debugging des Tests Échoués',['../md_README.html#autotoc_md100',1,'']]],
  ['tests_20échouent_20pourquoi_14',['Q : &quot;Mon code compile mais les tests échouent, pourquoi ?&quot;',['../md_README.html#autotoc_md152',1,'']]],
  ['tests_20automatiques_20complets_15',['F.1. Tests Automatiques Complets',['../md_README.html#autotoc_md64',1,'']]],
  ['tests_20d_20intégration_16',['2. Tests d&apos;Intégration',['../md_README.html#autotoc_md97',1,'']]],
  ['tests_20de_20comparaison_17',['4. Tests de Comparaison',['../md_README.html#autotoc_md99',1,'']]],
  ['tests_20de_20régression_18',['F.3. Tests de Régression',['../md_README.html#autotoc_md66',1,'']]],
  ['tests_20et_20validation_19',['🧪 Tests et Validation',['../md_README.html#autotoc_md90',1,'']]],
  ['tests_20et_20validation_20complète_20',['🏁 Phase Finale : Tests et Validation Complète',['../md_README.html#autotoc_md63',1,'']]],
  ['tests_20fourni_21',['Framework de Tests Fourni',['../md_README.html#autotoc_md91',1,'']]],
  ['tests_20personnalisés_22',['Création de Tests Personnalisés',['../md_README.html#autotoc_md105',1,'']]],
  ['tests_20recommandée_23',['Couverture de Tests Recommandée',['../md_README.html#autotoc_md106',1,'']]],
  ['tests_20unitaires_24',['1. Tests Unitaires',['../md_README.html#autotoc_md96',1,'']]],
  ['tests_20visuels_25',['3. Tests Visuels',['../md_README.html#autotoc_md98',1,'']]],
  ['thin_20tt_26',['1.6. Fonction &lt;tt&gt;thin&lt;/tt&gt;',['../md_README.html#autotoc_md37',1,'']]],
  ['thinning_27',['1. Squelettisation (Thinning)',['../md_README.html#autotoc_md137',1,'']]],
  ['thinning_5fstep_20tt_28',['1.5. Fonction &lt;tt&gt;thinning_step&lt;/tt&gt;',['../md_README.html#autotoc_md35',1,'']]],
  ['toi_20rien_20qu_20a_20toi_20_3a_29',['POUR CREER UNE BRANCHE (à toi, rien qu&apos;a toi) :',['../md_README.html#autotoc_md110',1,'']]],
  ['transitions_20tt_30',['1.3. Fonction &lt;tt&gt;transitions&lt;/tt&gt;',['../md_README.html#autotoc_md31',1,'']]],
  ['travail_31',['travail',['../md_README.html#autotoc_md70',1,'🔧 Méthodologie de Travail'],['../md_README.html#autotoc_md88',1,'Structure des Dossiers de Travail']]],
  ['tt_20apply_5frotation_20tt_32',['3.1. Fonction &lt;tt&gt;apply_rotation&lt;/tt&gt;',['../md_README.html#autotoc_md51',1,'']]],
  ['tt_20apply_5ftransformation_20tt_20minutie_20unique_33',['3.3. Fonction &lt;tt&gt;apply_transformation&lt;/tt&gt; (minutie unique)',['../md_README.html#autotoc_md55',1,'']]],
  ['tt_20apply_5ftransformation_20tt_20surcharge_20liste_34',['3.4. Fonction &lt;tt&gt;apply_transformation&lt;/tt&gt; (surcharge liste)',['../md_README.html#autotoc_md57',1,'']]],
  ['tt_20apply_5ftranslation_20tt_35',['3.2. Fonction &lt;tt&gt;apply_translation&lt;/tt&gt;',['../md_README.html#autotoc_md53',1,'']]],
  ['tt_20black_5fneighbours_20tt_36',['1.2. Fonction &lt;tt&gt;black_neighbours&lt;/tt&gt;',['../md_README.html#autotoc_md29',1,'']]],
  ['tt_20compute_5fangle_20tt_37',['2.3. Fonction &lt;tt&gt;compute_angle&lt;/tt&gt;',['../md_README.html#autotoc_md44',1,'']]],
  ['tt_20compute_5forientation_20tt_38',['2.4. Fonction &lt;tt&gt;compute_orientation&lt;/tt&gt;',['../md_README.html#autotoc_md46',1,'']]],
  ['tt_20compute_5fslope_20tt_39',['2.2. Fonction &lt;tt&gt;compute_slope&lt;/tt&gt;',['../md_README.html#autotoc_md42',1,'']]],
  ['tt_20connected_5fpixels_20tt_40',['2.1. Fonction &lt;tt&gt;connected_pixels&lt;/tt&gt;',['../md_README.html#autotoc_md40',1,'']]],
  ['tt_20extract_20tt_41',['2.5. Fonction &lt;tt&gt;extract&lt;/tt&gt;',['../md_README.html#autotoc_md48',1,'']]],
  ['tt_20get_5fneighbours_20tt_42',['1.1. Fonction &lt;tt&gt;get_neighbours&lt;/tt&gt;',['../md_README.html#autotoc_md27',1,'']]],
  ['tt_20identical_20tt_43',['1.4. Fonction &lt;tt&gt;identical&lt;/tt&gt;',['../md_README.html#autotoc_md33',1,'']]],
  ['tt_20match_20tt_20fonction_20finale_44',['3.6. Fonction &lt;tt&gt;match&lt;/tt&gt; (FONCTION FINALE)',['../md_README.html#autotoc_md61',1,'']]],
  ['tt_20matching_5fminutiae_5fcount_20tt_45',['3.5. Fonction &lt;tt&gt;matching_minutiae_count&lt;/tt&gt;',['../md_README.html#autotoc_md59',1,'']]],
  ['tt_20thin_20tt_46',['1.6. Fonction &lt;tt&gt;thin&lt;/tt&gt;',['../md_README.html#autotoc_md37',1,'']]],
  ['tt_20thinning_5fstep_20tt_47',['1.5. Fonction &lt;tt&gt;thinning_step&lt;/tt&gt;',['../md_README.html#autotoc_md35',1,'']]],
  ['tt_20transitions_20tt_48',['1.3. Fonction &lt;tt&gt;transitions&lt;/tt&gt;',['../md_README.html#autotoc_md31',1,'']]],
  ['types_20de_20commits_49',['Types de Commits',['../md_README.html#autotoc_md120',1,'']]],
  ['types_20de_20tests_50',['Types de Tests',['../md_README.html#autotoc_md95',1,'']]],
  ['types_20fournis_51',['Types Fournis',['../md_README.html#autotoc_md14',1,'']]]
];
